/*
This is the Class that defines the Entities for our Room.
Each entity will have an autogenerated ID, a Type and a value.
 */
package apps.raymond.friendswholift.StatSQLClasses;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;

@Entity(tableName = "stats_table")
public class StatEntity {

    @PrimaryKey(autoGenerate = true)
    private int id;

    @ColumnInfo(name = "statType")
    private String type;

    @ColumnInfo(name = "statValue")
    private double value;

    public StatEntity(String type, Double value){
        this.type = type;
        this.value = value;
    }

    public void setId(Integer id){
        this.id = id;
    }

    public int getId() {
        return this.id;
    }

    // ToDo: Check if we actually need these setters as they are set when the constructor is called.
    public void setType(String type){
        this.type = type;
    }

    public void setValue(double value){
        this.value = value;
    }

    public String getType() {
        return this.type;
    }

    public double getValue() {
        return this.value;
    }

}
