package apps.raymond.friendswholift;

import android.content.Intent;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.v4.view.ViewPager;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;

import apps.raymond.friendswholift.Login.LoginFrag;
import apps.raymond.friendswholift.Login.LoginPagerAdapter;
import apps.raymond.friendswholift.Login.SignUpFrag;

public class LoginActivity extends AppCompatActivity implements LoginFrag.SignIn, SignUpFrag.SignIn {
    private static final String TAG = "LoginActivity";
    public FirebaseAuth mAuth;

    @Override
    protected void onCreate(Bundle savedInstanceStance){
        super.onCreate(savedInstanceStance);
        setContentView(R.layout.login_screen);

        mAuth = FirebaseAuth.getInstance();

        //Adapter class that will generate the views to be displayed by the ViewPager.
        LoginPagerAdapter loginAdapter = new LoginPagerAdapter(getSupportFragmentManager());

        //The ViewPager that displays the views generated by loginAdapter.
        ViewPager mViewPager = findViewById(R.id.login_container);
        //We set the Adapter for this ViewPager (defined in login_screen.xml).
        mViewPager.setAdapter(loginAdapter);
    }

    @Override
    public void onStart(){
        super.onStart();
        Log.d(TAG,"LoginActivity started.");
    }
    @Override
    public void emailSignIn(final String username, final String password){
        Log.d(TAG,"Attempting to sign in via emailSignIn");
        mAuth.signInWithEmailAndPassword(username,password)
                .addOnCompleteListener(LoginActivity.this, new OnCompleteListener<AuthResult>(){
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task){
                        if(task.isSuccessful()){
                            Intent mainIntent = new Intent(LoginActivity.this,
                                    MainActivity.class);
                            startActivity(mainIntent);
                            finish();
                        } else {
                            Log.e(TAG, "Failed to log in user." +
                                    task.getException().getMessage());
                            Toast.makeText(LoginActivity.this,"Authentication failed.",
                                    Toast.LENGTH_LONG).show();
                        }
                    }
                });
    }

}
